app/urls.py
from django.urls import path
from . import views

app_name = "app"

urlpatterns = [
    #path('', views.home, name="homepage"),
    #path('detail/<int:pk>/', views.detail, name="detail"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path('', views.HomeListView.as_view(), name="home"),
    path('detail/<int:pk>/', views.ContactDetailView.as_view(), name="detail"),
    path('search/', views.search, name="search"),
    path('contacts/create/', views.ContactCreateView.as_view(), name="create"),
    path('contacts/update/<int:pk>/', views.ContactUpdateView.as_view(), name="update"),
    path('contacts/delete/<int:pk>/', views.ContactDeleteView.as_view(), name="delete")
]

contacts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Contacts"
admin.site.index_title = "Welcome"

app/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
# Create your models here.

User = get_user_model()


class Contact(models.Model):
    manager = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    email = models.EmailField()
    phone = models.IntegerField()
    info = models.CharField(max_length=20)
    gender = models.CharField(max_length=50, choices=(
        ('male', 'Male',),
        ('female', 'Female',),
    ))
    image = models.ImageField(upload_to='images/', blank=True)
    date_added = models.DateTimeField(default=timezone.now)
    
    class Meta:
        ordering = ('-date_added',)
    def __str__(self):
        return self.name

app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Q
from django.urls import reverse_lazy

from .models import Contact


# Create your views here.

#def home(request):
#    return render(request, "index.html", {'contacts': Contact.objects.all()})


#def detail(request, pk):
#    context = {
#        'contact': get_object_or_404(Contact, pk=pk)
#    }
#    return render(request, "detail.html", context)

class ContactDetailView(LoginRequiredMixin,DetailView):
    context_object_name = "contact"
    model = Contact
    template_name = "detail.html"


class HomeListView(LoginRequiredMixin, ListView):
    template_name = "index.html"
    model = Contact
    context_object_name = "contacts"

    def get_queryset(self):
        contacts = super().get_queryset()
        return contacts.filter(manager=self.request.user)

class ContactCreateView(LoginRequiredMixin ,CreateView):
    model = Contact
    template_name = 'create.html'
    fields = ['name', 'email', 'phone', 'info', 'gender', 'image']

    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.manager = self.request.user
        instance.save()
        messages.success(self.request, 'Your contact has been successfully created')
        return redirect("app:home")


class ContactUpdateView(LoginRequiredMixin, UpdateView):
    model = Contact
    template_name = 'update.html'
    fields = ['name', 'email', 'phone', 'info', 'gender', 'image']
    success_url = "/"

    def form_valid(self, form):
        instance = form.save()
        messages.success(self.request, "Your contact has been updated successfully!")
        return redirect("app:detail", instance.pk)


class ContactDeleteView(LoginRequiredMixin, DeleteView):
    model = Contact
    template_name = "delete.html"
    success_url = '/'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Your contact has been successfully deleted!')
        return super().delete(self, request, *args, **kwargs)

class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy("app:home")

@login_required
def search(request):
    if request.GET:
        search_term = request.GET.get('search_term')
        contacts = Contact.objects.filter(
            Q(name__icontains=search_term) |
            Q(email__icontains=search_term) |
            Q(info__icontains=search_term)
        ).filter(manager=request.user)
        return render(request, "search.html", {'contacts': contacts, 'search_term': search_term})
    redirect("app:home")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static './css/bootstrap.min.css' %}" />
    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    <!-- Fonts & Icons -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" />
    <title>
        {% block title %}
        My Contacts
        {% endblock %}
    </title>
</head>

<body>
    <!-- Navbar -->

    <nav>
        <a class="logo" href="{% url 'app:home' %}">
            <i class="fas fa-user-circle"></i>&nbsp;Contacts
        </a>

        <p class="feature-link m-0 p-0">
            {% if request.user.is_authenticated %}
            <span class="mr-4"><h3 class="m-0 text-white text">
                <i class="fas fa-sign-in-alt "></i>&nbsp; {{ request.user.username }}
                </h3>
            </span>
            <a href="{% url 'logout' %}" class="mr-4 text-white">
                <i class="fas fa-sign-in-alt"></i>&nbsp; Log out
            </a>
            <a href="{% url 'app:create' %}" class="mr-4 text-white">
                <i class="fas fa-plus"></i>&nbsp; Add Contact
            </a>
            {% else %}
            <a href="{% url 'app:signup' %}" class="mr-4 text-white">
                <i class="fas fa-user-plus"></i>&nbsp; Sign Up
            </a>
            <a href="{% url 'login' %}" class="mr-4 text-white">
                <i class="fas fa-sign-in-alt"></i>&nbsp; Login
            </a>
            {% endif %}

        </p>


        <form class="form-inline my-2" action="{% url 'app:search' %}" method="GET">
            <input class="form-control search-box" type="search" placeholder="Find contacts..." value="{{ search_term }}" name="search_term" />

        </form>
    </nav>
    <!-- Navbar ends -->
    <br />
    {% include "partials/_message.html" %}

    {% block content %}

    {% endblock %}

    <!-- footer -->
    <footer class="mt-4 p-2">
        <p class="text-center p-1 m-0">&copy; My Contacts 2019</p>
    </footer>
    <!-- footer ends -->
   

    <!-- scripts -->
    <script>
        var close_elements = document.getElementsByClassName("close");
        for(let i=0; i<close_elements.length; i++){
            close_elements[i].addEventListener("click", function(e){
                this.parentElement.style.display = "none";
            });
        }
    </script>
</body>

</html>

templates/create.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block title %}
Create a new Contact
{% endblock %}

{% block content %}
<div class="container">
    <h2 class="heading font-weight-light text-center">Create a New Contact</h2>
    <hr />
</div>
<div class="container w-25 card p-4 mt-4">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="w-100 text-white text-center my-2 btn btn-info" type="submit" value="create">

    </form>
</div>

{% endblock %}

templates/delete.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block title %}
{% if contact.manager == request.user %}
Delete {{ contact.name }}
{% else %}
Permission Error
{% endif %}
{% endblock %}

{% block content %}
{% if contact.manager == request.user %}
<div class="container">
    <h2 class="heading font-weight-light text-center">Delete {{ contact.name }}</h2>
    <hr />
</div>
<div class="container w-25 card p-4 mt-4">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="w-100 text-white text-center my-2 btn btn-danger" type="submit" value="Delete">

    </form>
</div>
{% else %}
<div class="container">
    <h2 class="heading font-weight-light text-center">You do not have permission to access this page</h2>
    <hr />
</div>
{% endif %}

{% endblock %}

templates/detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
{% if contact.manager == request.user %}

{{ contact.name }}
{% else %}
Permission Error
{% endif %}
{% endblock %}

{% block content %}
{% if contact.manager == request.user %}
<!-- Main Section ends-->
<!-- Main Section -->
<div class="container">
    <h2 class="heading font-weight-light text-center"> {{ contact.name }} </h2>
    <hr />
</div>

<div class="container main-part">
    <!-- Card for details -->
    {% include "partials/_card.html" %}

</div>
<div class="container mt-3">
    <h5 class="text-center my-3 font-weight-lighter">Date Added: &nbsp; {{ contact.date_added }}</h5>
    <p class="text-center text-light">
        <a class="btn btn-info px-5" href="{% url 'app:update' contact.id %}">
            <i class="fas fa-edit"></i> &nbsp; Update
        </a>
        &nbsp; &nbsp;&nbsp;
        <a class="btn btn-danger px-5" href="{% url 'app:delete' contact.id %}">
            <i class="fas fa-trash-alt"></i> &nbsp; Delete
        </a>
    </p>
</div>
{% else %}
<div class="container">
    <h2 class="heading font-weight-light text-center"> You don't have access to this page </h2>
    <hr />
</div>

{% endif %}
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% load static %}

{% block title %}
My contacts
{% endblock %}


{% block content %}
<!-- Main Section -->
<div class="container">
  <h3 class="heading font-weight-light">Here are your contacts</h3>
  <hr />
</div>

<div class="container main-part">
  {% if contacts %}
  {% for contact in contacts %}
    {% include "partials/_card.html" %}
   <!-- Card for details ends -->
    {% endfor %}
    
  {% else %}
    <p class="d-block font-weight-light header my-2 mx-2">You have not saved any contacts yet!</p>
  {% endif %}
  
 

  
</div>
{% endblock %}

templates/partials/_card.html
{% load static %}

{% if contact.gender == 'male' %}
      <!-- Card for details -->
  <div class="card my-2 mx-2 boy-card {% if 'detail' in request.path %}mx-auto w-25{% endif %}">
      <img src="
        {% if contact.image %}
          {{ contact.image.url }}
        {% else %}
          {% static 'images/boy.png' %}
        {% endif %}" 
        class="img-fluid" 
      />
      <div class="card-header">
        <a href="{% url 'app:detail' contact.id %}" class="text-white header-link">
          <i class="fas fa-mars mr-2"></i>
          {{ contact.name }}
        </a>
      </div>
      <div class="card-body pb-0">
        <p>
          <i class="fas fa-at mr-2"></i>
          <a href="{{ contact.email }}">{{ contact.email }}</a>
        </p>
        <p>
          <i class="fas fa-phone mr-2"></i>
          <a href="tel:{{ contact.phone }}">{{ contact.phone }}</a>
        </p>
        <p><i class="fas fa-info-circle mr-2"></i> {{ contact.info }}</p>
      </div>
    </div>
    {% else %}
    <div class="card my-2 mx-2 girl-card {% if 'detail' in request.path %}mx-auto w-25{% endif %}">
        <img src="
          {% if contact.image %}
            {{ contact.image.url }}
          {% else %}
            {% static 'images/girl.png' %}
          {% endif %}"
          class="img-fluid" 
        />
        <div class="card-header">
          <a href="{% url 'app:detail' contact.id %}" class="text-white header-link"><i class="fas fa-venus mr-2"></i> {{ contact.name }}</a>
        </div>
        <div class="card-body pb-0">
          <p>
            <i class="fas fa-at mr-2"></i>
            <a href="mailto:{{ contact.email }}">{{ contact.email }}</a>
          </p>
          <p>
            <i class="fas fa-phone mr-2"></i>
            <a href="tel:{{ contact.phone }}">{{ contact.phone }}</a>
          </p>
          <p><i class="fas fa-info-circle mr-2"></i> {{ contact.info }}</p>
        </div>
      </div>
    

    {% endif %}

templates/partials/_message.html
{% if messages %}
{% for message in messages %}
<div class="container">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" date-dismiss="alert" aria-label="close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>

{% endfor %}
{% endif %}

templates/search.html
{% extends "base.html" %}

{% load static %}

{% block title %}
Search
{% endblock %}

{% block content %}
<!-- Main Section -->
<div class="container">
  <h3 class="heading font-weight-light">Search results for {{ search_term }}</h3>
  <hr />
</div>

<div class="container main-part">
  <!-- Card for details -->
  {% if contacts %}
  {% for contact in contacts %}
    {% include "partials/_card.html" %}
   <!-- Card for details ends -->
    {% endfor %}
    
  {% else %}
    <p class="d-block font-weight-light header my-2 mx-2">No contact matches your search</p>
  {% endif %}
  
 
</div>
<!-- Main Section ends-->
{% endblock %}

templates/update.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% block title %}
{% if contact.manager == request.user %}
Update {{ contact.name }} 
{% else %}
Permission Error
{% endif %}
{% endblock %}

{% block content %}
{% if contact.manager == request.user %}
<div class="container">
    <h2 class="heading font-weight-light text-center">Update {{ contact.name }}</h2>
    <hr />
</div>
<div class="container w-25 card p-4 mt-4">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="w-100 text-white text-center my-2 btn btn-info" type="submit" value="Update">

    </form>
</div>
{% else %}
<div class="container">
        <h2 class="heading font-weight-light text-center">You do not have permission to access this page</h2>
        <hr />
    </div>
    {% endif %}

{% endblock %}